application: imposing-eye
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
# Serve Theme static resources.
- url: /themes/(.+)/assets/(css|js|fonts|img)/(.+)
  static_files: themes/\1/assets/\2/\3
  upload: themes/(.+)/assets/(css|js|fonts|img)/(.+)

# Serve Core static resources.
- url: /core/modules/(.+)/assets/(.+)
  static_files: core/modules/\1/assets/\2
  upload: core/modules/(.+)/assets/(.+)

# Load the index php
- url: /.*
  script: index.php

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# PageSpeed overide settings
pagespeed:
  enabled_rewriters:
  - MinifyCss
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls